plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs.kotlin'
    id 'dagger.hilt.android.plugin'
}
android {
    compileSdkVersion 34

    defaultConfig {
        applicationId "ibm2187.dev.pixabay"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            debuggable true

        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures{
        viewBinding true
        buildConfig true
    }
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
    namespace 'ibm2187.dev.pixabay'
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.swiperefreshlayout

    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.common.java8
    implementation libs.androidx.lifecycle.runtime.ktx

    implementation libs.coil

    //retrofit
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.gson
    implementation libs.okhttp.logging.interceptor

    // Navigation Component
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    //hilt
    implementation libs.hilt.android
    kapt libs.hilt.compiler


    //testing
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
    testImplementation libs.okhttp.mockwebserver
    testImplementation libs.junit.jupiter.api
    testRuntimeOnly libs.junit.jupiter.engine

}
kapt {
    correctErrorTypes true
}